### ISSUE TITLE
Crashes when an image is loaded.

### ISSUE THREAD

**Issue by seanofw** [taotao54321/QoiVisualizer#1]
No matter what image I load, or what browser I load it in, the program seems to immediately crash with a panic in the console.

![image](https://user-images.githubusercontent.com/981716/144789421-12d1193e-c4d8-44f4-9267-28163ed045e1.png)

I've tried in the latest versions of both Firefox (94.0.2) and Chrome (96.0.4664.45).

**Comment by taotao54321** [comment]
Thank you for reporting.
I confirmed that this app crashes when I load any JPEG files. Considering the error message, it seems to be related to image-rs/image#1496.

I fixed `Cargo.toml` to disable `jpeg_rayon` feature of `image` crate, and I successfully loaded a JPEG file in the app.
Already I deployed the new version. Does it fix the issue for you?

**Comment by seanofw** [comment]
Yes, it's working now!  Thank you for this useful tool.
